menu:
  Blog: /
  Archive: /archives/
  About: /about/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
# startyear: 2015

# widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
#   - category
#   - tag
# TODO category
